### ISSUE TITLE
enable OpenMP 4.5 for compilers besides Cray

### ISSUE THREAD

**Issue by jeffhammond** [UoB-HPC/GPU-STREAM#18]
I'm not a CMake guru but this project should test for OpenMP 4.5 compiler support generically rather than just associate this implementation with the Cray toolchain.

http://www.openmp.org/resources/openmp-compilers/ has the full list, but at least GCC 6.1+ and Intel 17+ support OpenMP 4.5 and I just confirmed that GCC 6.2.0 can correctly run `gpu-stream-omp45`.

```
$ git diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index efee733..574fcc3 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -118,12 +118,12 @@ endif ()
 #-------------------------------------------------------------------------------
 # OpenMP 4.5
 #-------------------------------------------------------------------------------
-if ("${CMAKE_CXX_COMPILER_ID}" MATCHES "Cray")
-  if (CMAKE_CXX_COMPILER_VERSION VERSION_GREATER 4.5)
+#if ("${CMAKE_CXX_COMPILER_ID}" MATCHES "Cray")
+#  if (CMAKE_CXX_COMPILER_VERSION VERSION_GREATER 4.5)
     add_executable(gpu-stream-omp45 main.cpp OMP45Stream.cpp)
     target_compile_definitions(gpu-stream-omp45 PUBLIC OMP45)
-  endif ()
-endif ()
+#  endif ()
+#endif ()
```

**Comment by tomdeakin** [comment]
This should be solved in v3.1. Additionally in v3.0 we changed the structure on the OpenMP code to allow building for CPUs and GPUs via compiler preprocessor switch rather than separate source.
