### ISSUE TITLE
how to contribute?

### ISSUE THREAD

**Issue by psteinb** [UoB-HPC/GPU-STREAM#22]
it was mentioned in #21 that GPU-STREAM is switching to a Makefile based build (I am not sure of the reasons for this as pointed out there). I wanted to create a PR for contributing a HCC compiled memory benchmark based on rocm. How should I go about it? Use a Makefile or integrate it into the cmake setup of this repo?

**Comment by jrprice** [comment]
I'd just target CMake for now if it works for you, until we've actually decided what we're going to do with the build system.

**Comment by tomdeakin** [comment]
In v.3.1 we switched to simple Makefiles. We have one for HIP, so it should be simple to use this as a basis for the HCC version.

**Comment by psteinb** [comment]
I'll look into this today.
Best,
P
